In [0]:
sc

In [0]:
print(spark)

In [0]:
pivot_df = spark.read.csv("dbfs:/FileStore/tables/Pyspark_Task-1.csv",header=True,inferSchema = True)
pivot_df.show()

+-------+----------+--------+--------+--------+--------+--------+------+------+------+------+------+
|Product|Plant Name|Sales_18|Sales_19|Sales_20|Sales_21|Sales_22|Inv_18|Inv_19|Inv_20|Inv_21|Inv_22|
+-------+----------+--------+--------+--------+--------+--------+------+------+------+------+------+
|     P1|       PL1|   20000|   25000|   19000|   22000|   23000| 13000| 12000| 13000| 13500| 14000|
|     P2|       PL1|   80000|   90000|   75000|   78000|  100000| 18000| 18000| 18000| 18000| 18000|
|     P3|       PL3|   35000|   32000|   56000|   40000|   42000| 17000| 20000| 16000| 15000| 15000|
|     P4|       PL2|   15000|   23000|   42000|   12000|   13000| 13000| 13000| 13000| 13000| 13000|
|     P5|       PL1|   85000|   19000|   24000|   15000|   13000| 20000| 22000| 23000| 23000| 21000|
+-------+----------+--------+--------+--------+--------+--------+------+------+------+------+------+

In [0]:
from pyspark.sql import *
from pyspark.sql import SparkSession
from pyspark.sql.functions import expr

In [0]:
unpivotExpr = "stack(5,'PL1',PL1,'PL2',PL2,'PL3',PL3,'PL4',PL4,'PL5',PL5) as (PlantName,Total)"
unPivotDF = pivot_df.select("Product", expr(unpivotExpr)) \
    .where("Total is not null")
unPivotDF.show(truncate=False)
unPivotDF.show()

---------------------------------------------------------------------------
AnalysisException                         Traceback (most recent call last)
<command-3434194743104143> in <module>
      1 unpivotExpr = "stack(5,'PL1',PL1,'PL2',PL2,'PL3',PL3,'PL4',PL4,'PL5',PL5) as (PlantName,Total)"
----> 2 unPivotDF = pivot_df.select("Product", expr(unpivotExpr)) \
      3     .where("Total is not null")
      4 unPivotDF.show(truncate=False)
      5 unPivotDF.show()

/databricks/spark/python/pyspark/sql/dataframe.py in select(self, *cols)
   1824         [Row(name='Alice', age=12), Row(name='Bob', age=15)]
   1825         """
-> 1826         jdf = self._jdf.select(self._jcols(*cols))
   1827         return DataFrame(jdf, self.sql_ctx)
   1828

/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1302
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    121                 # Hide where the exception came from that shows a non-Pythonic
    122                 # JVM exception message.
--> 123                 raise converted from None
    124             else:
    125                 raise

AnalysisException: Column 'PL1' does not exist. Did you mean one of the following? [Inv_18, Inv_19, Inv_21, Inv_20, Inv_22, Product, Sales_18, Sales_19, Sales_21, Sales_20, Sales_22, Plant Name]; line 1 pos 14;
'Project [Product#335, 'stack(5, PL1, 'PL1, PL2, 'PL2, PL3, 'PL3, PL4, 'PL4, PL5, 'PL5) AS ArrayBuffer(PlantName, Total)]
+- Relation [Product#335,Plant Name#336,Sales_18#337,Sales_19#338,Sales_20#339,Sales_21#340,Sales_22#341,Inv_18#342,Inv_19#343,Inv_20#344,Inv_21#345,Inv_22#346] csv